version: 0.1
phases:
  build:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket my-demo-test-bucket-us-east-1 --output-template-file outputSamTemplate.yaml
artifacts:
  files:
    - outputSamTemplate.yaml
  name: outputSamTemplate.yaml
  discard-paths: yes